Merge JS2 to Main
pretzL/DevMeets pull request #76
Opened 2022-10-10 21:26 UTC by pretzL

2022-10-11 10:04 UTC, Sigvel commented
# Peer Review

## JS / Functionality
### Landing page / profile page
The profile landing page looks nice, you get a feed of all the posts.
on the profile page the form doesnt work and it only has body, but i guess it is intended.

**What works fine.**
- posting comments works fine.
- View a post's comments looks nice.
- liking post in view post works fine.
- updating banner works great.

**What does not work fine**

- Would enjoy a button to bring me back from view post comments.
- The error message for the avatar update is bit low, couldnt se it when i was editing until i went further down.
- Honestly i dont know what the clear button should do, i expect it to clear the input but doesnt, would just remove it for now if it should not be usable tbh.

### Homepage

**What works fine.**
- editing a post works fine, and i really like the setup
- creating post works fine, other than what i stated down below.
- deleting post works great
- i love your sorting functionality.

**What does not work fine**
- When i made a post, i didnt get the title back, i only got the body image and tags and can only view body image and tags from others.

### in general
The site functions well and i like alot of the functionality, the code looks good, and the folder structure is well structured in my opinion.

What i am missing is more JsDocs documentation, it is easier to hover over functions and see what gets passed in or what they do and how they work, its easier to manage the code and understand it faster with it. Would recommend to take a look at it, it is also a criteria.
Also when you come back to the code a bit later its easier to get back into your code.

**Own opinions:**

- When i search i get what includes in body, i can suggest an option, that is to use include on name, and startsWith() on the body and maybe title.. might get more accurate search results.

## HTML / Look

- The avatar image scales out of place on the profile page.
- The most buttons i hover over doesnt become a pointer, i would go over the buttons just because it take's away the feel of the website.
- You could also take away the login button when people are logged in at home and my profile page, just doesnt feel right to have it there.
- On smaller screens the hamburger menu does not work.. and you cant navigate because of this.

## in general

The site looks good, and there is not alot of issues. But i would definetly look at the size of the login background image it is 2 MB, you should try to get it down to 200kb max 300.
The image placeholder banner is a bit large too and is around 4000kb.

**The issue:** 
This will cause slow loading speed.

For the image issue i recommend to use the **image** tab then **image size** or **bildestørrelse** in photoshop and shrink it a bit.
And then use the export to web and take down the quality if needed.


### Overall the site looks good, and good luck on the assignment !.

2022-10-12 06:13 UTC, Fermain commented
<img width="839" alt="image" src="https://user-images.githubusercontent.com/10801540/195264072-32f9e76a-ddfb-4fe8-a213-e565b1a4f916.png">

Unable to edit post if there is no media present due to validator

2022-10-12 06:23 UTC, Fermain requested changes
This is a really high quality submission that looks and feels like a real application. There are some issues to be resolved (setTimeout mostly) and there are improvements to be made in terms of code organisation and structure. (await > then).

With the setTimeout issue and update post issues solved this is a very, very comfortable pass.

2022-10-12 06:23 UTC, Fermain commented on src/js/posts/createComment.mjs
> +        setTimeout(() => {
This is a sign that async/await is not being used properly. Check the `teacher-review` branch for my solution to this.

2022-10-12 06:23 UTC, Fermain commented on src/js/posts/createPost.mjs
> +        setTimeout(() => {
Here too

2022-10-12 06:23 UTC, Fermain commented on src/js/posts/createReactions.mjs
> +        setTimeout(() => {
And here

2022-10-12 06:23 UTC, Fermain commented on src/js/posts/editPost.mjs
> +        setTimeout(() => {
Here too!

2022-10-12 06:23 UTC, Fermain commented on src/js/posts/getPostToDelete.mjs
> +      setTimeout(location.reload.bind(location), 1000);
You guessed it

2022-10-12 06:23 UTC, Fermain commented on src/js/user/profiles/follow-unfollow/requests.mjs
> +        setTimeout(() => {
Hello darkness my old friend

2022-10-12 06:23 UTC, Fermain commented on src/js/user/profiles/updateProfile.mjs
> +        setTimeout(() => {
I've come to talk with you again

2022-10-12 06:23 UTC, Fermain commented on src/js/user/registerUser.mjs
> +          setTimeout(() => {
Because a vision softly creeping,
Left its seeds while I was sleeping

2022-10-31 06:17 UTC, Fermain requested changes
It looks like you have some artefacts left over from installing a bundler (out directory).

If these files aren't being used they should be removed from history. It's conventional when using a bundler to ignore the output directory so that this content is not included in a pull request.

Otherwise, the code is working great.

2022-11-03 13:29 UTC, merged